# Generated by Django 6.0.3 on 2026-05-13 15:35

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_remove_product_base_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productgallery',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='gallery_image'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='variant_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='variant_image'),
        ),
    ]
