# Generated by Django 6.0.3 on 2026-05-14 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_alter_productgallery_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='room',
        ),
        migrations.AddField(
            model_name='product',
            name='room',
            field=models.ManyToManyField(related_name='products', to='catalog.room'),
        ),
    ]
