# Generated by Django 6.0.3 on 2026-05-15 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_product_is_archived'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='variant_image',
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='price_override',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
