# Generated by Django 6.0.3 on 2026-05-15 09:14

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_remove_productvariant_variant_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='variant_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='variant_image'),
        ),
    ]
