# Generated by Django 6.0.3 on 2026-05-19 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_product_base_price_variantgroup_variantoption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='price_override',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='extra_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
