# Generated by Django 6.0.3 on 2026-05-23 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_remove_productvariant_price_override_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='discount_price',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
