# Generated by Django 6.0.3 on 2026-07-18 04:30

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_remove_productvariant_discount_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variantoption',
            name='variant_group',
        ),
        migrations.RemoveField(
            model_name='product',
            name='base_price',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='extra_price',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='is_out_of_stock',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='sku',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='stock_quantity',
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='variant_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='VariantCombination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('sku', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('cover_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='combo_cover_image')),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combinations', to='catalog.product')),
                ('variants', models.ManyToManyField(related_name='combinations', to='catalog.productvariant')),
            ],
        ),
        migrations.DeleteModel(
            name='VariantGroup',
        ),
        migrations.DeleteModel(
            name='VariantOption',
        ),
    ]
