# Generated by Django 6.0.3 on 2026-07-20 09:31

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_product_base_price_productvariant_discount_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='base_price',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='extra_price',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='sku',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='stock_quantity',
        ),
        migrations.RemoveField(
            model_name='variantcombination',
            name='cover_image',
        ),
        migrations.AddField(
            model_name='variantcombination',
            name='main_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='combination_main_image'),
        ),
        migrations.CreateModel(
            name='CombinationGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='combination_gallery_image')),
                ('combination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='catalog.variantcombination')),
            ],
        ),
    ]
