# Generated by Django 6.0.3 on 2026-05-21 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_remove_productvariant_price_override_and_more'),
        ('shop', '0004_wishlist_unique_user_variant_wishlist'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='wishlist',
            name='unique_user_variant_wishlist',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='selected_variants',
            field=models.ManyToManyField(blank=True, related_name='wishlist_combinations', to='catalog.productvariant'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='variant_combination',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
