# Generated by Django 6.0.3 on 2026-05-18 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_wishlist_variant'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together=set(),
        ),
    ]
