# Generated by Django 6.0.3 on 2026-05-18 04:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_productvariant_is_default'),
        ('shop', '0003_alter_wishlist_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='wishlist',
            constraint=models.UniqueConstraint(fields=('user', 'variant'), name='unique_user_variant_wishlist'),
        ),
    ]
