# Generated by Django 6.0.3 on 2026-07-18 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_product_base_price_productvariant_discount_amount_and_more'),
        ('shop', '0005_remove_wishlist_unique_user_variant_wishlist_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='selected_variants',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='variant',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='variant_combination',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='combination',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalog.variantcombination'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='wishlist',
            constraint=models.UniqueConstraint(fields=('user', 'combination'), name='unique_user_combination_wishlist'),
        ),
    ]
