# Generated by Django 6.0.3 on 2026-07-20 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at']},
        ),
    ]
