# Generated by Django 6.0.3 on 2026-06-27 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0002_coupon_discount_type_coupon_max_discount_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='applicable_categories',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='applicable_products',
        ),
    ]
