# Generated by Django 6.0.3 on 2026-06-09 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='tax_amount',
        ),
    ]
