# Generated by Django 6.0.3 on 2026-06-10 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_orders', '0002_remove_order_tax_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
