# Generated by Django 6.0.3 on 2026-06-19 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_orders', '0006_order_delivery_city_order_delivery_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('CANCELLED', 'Cancelled'), ('RETURN_REQUESTED', 'Return Requested'), ('RETURNED', 'Returned'), ('RETURN_REJECTED', 'Return Rejected')], default='ACTIVE', max_length=20),
        ),
    ]
