# Generated by Django 6.0.3 on 2026-06-23 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_orders', '0008_alter_order_payment_method_orderpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'Cash On Delivery'), ('RAZORPAY', 'Razorpay'), ('WALLET', 'Wallet')], default='COD', max_length=20),
        ),
    ]
