# Generated by Django 6.0.3 on 2026-09-15 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_orders', '0012_backfill_orderitem_combinations'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='return_requested_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
