# Generated by Django 6.0.3 on 2026-09-15 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_orders', '0013_orderitem_return_requested_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='return_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
