# Generated by Django 6.0.3 on 2026-05-19 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='selected_options',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
