# Generated by Django 6.0.3 on 2026-05-21 13:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cart_selected_options'),
        ('catalog', '0018_remove_productvariant_price_override_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.UniqueConstraint(fields=('user', 'variant', 'selected_options'), name='unique_user_variant_combination_cart'),
        ),
    ]
