# Generated by Django 6.0.3 on 2026-05-11 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_product_productvariant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productvariant',
            old_name='stock',
            new_name='stock_quantity',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='color',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='price',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='size',
        ),
        migrations.AddField(
            model_name='product',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='is_out_of_stock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='price_override',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='variant_name',
            field=models.CharField(default='Default', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productvariant',
            name='variant_type',
            field=models.CharField(default='Type', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productvariant',
            name='variant_value',
            field=models.CharField(default='Value', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.room'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='variant_image',
            field=models.ImageField(blank=True, null=True, upload_to='variants/'),
        ),
    ]
