# Generated by Django 6.0.3 on 2026-07-18 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_remove_variantoption_variant_group_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together={('product', 'variant_type', 'variant_value')},
        ),
    ]
