# Generated by Django 6.0.3 on 2026-05-29 16:30

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_remove_productvariant_discount_price_and_more'),
        ('inspiration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspirationStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='InspirationTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='inspirationboard',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='inspirations', to='catalog.category'),
        ),
        migrations.AddField(
            model_name='inspirationboard',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inspirationboard',
            name='priority',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inspirationboard',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='inspiration_boards', to='catalog.product'),
        ),
        migrations.AddField(
            model_name='inspirationboard',
            name='rooms',
            field=models.ManyToManyField(blank=True, related_name='inspirations', to='catalog.room'),
        ),
        migrations.AddField(
            model_name='inspirationboard',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='inspirationboard',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='inspirationboard',
            name='cover_image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='inspiration_cover'),
        ),
        migrations.CreateModel(
            name='InspirationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='inspiration_gallery')),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='inspiration.inspirationboard')),
            ],
        ),
        migrations.AddField(
            model_name='inspirationboard',
            name='style',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inspiration.inspirationstyle'),
        ),
        migrations.AddField(
            model_name='inspirationboard',
            name='tags',
            field=models.ManyToManyField(blank=True, to='inspiration.inspirationtag'),
        ),
        migrations.DeleteModel(
            name='InspirationItem',
        ),
    ]
