# Generated by Django 6.0.3 on 2026-06-04 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspiration', '0002_inspirationstyle_inspirationtag_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inspirationboard',
            options={'ordering': ['priority', '-created_at']},
        ),
    ]
