# Generated by Django 6.0.3 on 2026-07-08 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_remove_productvariant_discount_price_and_more'),
        ('inspiration', '0003_alter_inspirationboard_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inspirationimage',
            options={'ordering': ['display_order']},
        ),
        migrations.AddField(
            model_name='inspirationimage',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspiration_images', to='catalog.product'),
        ),
    ]
