# Generated by Django 6.0.3 on 2026-07-18 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_orders', '0010_alter_order_status'),
        ('catalog', '0020_remove_variantoption_variant_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='combination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.variantcombination'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.productvariant'),
        ),
    ]
