# Generated by Django 6.0.3 on 2026-09-16 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_orders', '0014_alter_orderitem_return_requested_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='original_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
