# Generated by Django 6.0.3 on 2026-06-26 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referraloffer',
            name='token',
            field=models.CharField(default='ac2ea2c3d3a54ffaa89da2bb6adb917a', max_length=64, unique=True),
        ),
    ]
