# Generated by Django 6.0.3 on 2026-06-27 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_alter_referraloffer_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referraloffer',
            name='token',
            field=models.CharField(default='fede5041fd1f463cb7d261247e5338d5', max_length=64, unique=True),
        ),
    ]
