# Generated by Django 6.0.3 on 2026-06-27 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_alter_referraloffer_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referraloffer',
            name='token',
            field=models.CharField(default='e319cfc380da42b8817613634c437a44', max_length=64, unique=True),
        ),
    ]
