# Generated by Django 6.0.3 on 2026-07-02 03:47

import apps.admin_side.offers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0004_alter_referraloffer_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryoffer',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='categoryoffer',
            name='discount_type',
            field=models.CharField(choices=[('percent', 'Percentage'), ('fixed', 'Fixed Amount')], default='percent', max_length=10),
        ),
        migrations.AddField(
            model_name='categoryoffer',
            name='name',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='productoffer',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='productoffer',
            name='discount_type',
            field=models.CharField(choices=[('percent', 'Percentage'), ('fixed', 'Fixed Amount')], default='percent', max_length=10),
        ),
        migrations.AddField(
            model_name='productoffer',
            name='name',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='categoryoffer',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='productoffer',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='referraloffer',
            name='token',
            field=models.CharField(default=apps.admin_side.offers.models.generate_token, max_length=64, unique=True),
        ),
    ]
